-- Harden RLS for payroll and related HR-finance tables.
-- Removes broad/unsafe policies and replaces with admin-only policies.

-- ---------------------------------------------------------------------------
-- Helper: identify payroll admins from JWT claims
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.is_payroll_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
  SELECT
    COALESCE(auth.role() = 'service_role', FALSE)
    OR COALESCE(auth.jwt()->>'role' IN ('admin', 'payroll_admin', 'payroll_manager'), FALSE)
    OR COALESCE(auth.jwt()->'app_metadata'->>'role' IN ('admin', 'payroll_admin', 'payroll_manager'), FALSE)
    OR EXISTS (
      SELECT 1
      FROM jsonb_array_elements_text(COALESCE(auth.jwt()->'app_metadata'->'roles', '[]'::jsonb)) AS r(role_name)
      WHERE r.role_name IN ('admin', 'payroll_admin', 'payroll_manager')
    );
$$;

-- ---------------------------------------------------------------------------
-- Remove previous broad payroll policies generated by baseline migration
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  t RECORD;
BEGIN
  FOR t IN
    SELECT tablename
    FROM pg_tables
    WHERE schemaname = 'public'
      AND tablename IN (
        'payroll_periods','payroll_runs','payroll_run_employees','payroll_run_lines',
        'leave_credit_policies','leave_credit_ledger','leave_balance_yearly',
        'overtime_entries','overtime_overrides',
        'deduction_catalog','employee_recurring_deductions','employee_one_time_deductions',
        'loan_accounts','loan_installments','loan_transactions',
        'payroll_adjustments','payroll_exceptions','manual_override_audit','payslip_snapshots',
        'payroll_records','payroll_deduction_settings'
      )
  LOOP
    -- Policy name used in 20260415132500_add_payroll_helpers_and_rls_baseline.sql
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I;', 'auth_full_' || t.tablename, t.tablename);
    -- Any legacy broad policy accidentally created elsewhere
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I;', 'Enable all for authenticated users', t.tablename);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I;', 'Enable all for anon', t.tablename);
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- Ensure RLS is enabled on payroll domain tables
-- ---------------------------------------------------------------------------
ALTER TABLE IF EXISTS public.payroll_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payroll_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payroll_run_employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payroll_run_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.leave_credit_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.leave_credit_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.leave_balance_yearly ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.overtime_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.overtime_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.deduction_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.employee_recurring_deductions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.employee_one_time_deductions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.loan_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.loan_installments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.loan_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payroll_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payroll_exceptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.manual_override_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payslip_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payroll_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payroll_deduction_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.leave_requests ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- Create strict admin-only policies for payroll domain
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  t RECORD;
BEGIN
  FOR t IN
    SELECT tablename
    FROM pg_tables
    WHERE schemaname = 'public'
      AND tablename IN (
        'payroll_periods','payroll_runs','payroll_run_employees','payroll_run_lines',
        'leave_credit_policies','leave_credit_ledger','leave_balance_yearly',
        'overtime_entries','overtime_overrides',
        'deduction_catalog','employee_recurring_deductions','employee_one_time_deductions',
        'loan_accounts','loan_installments','loan_transactions',
        'payroll_adjustments','payroll_exceptions','manual_override_audit','payslip_snapshots',
        'payroll_records','payroll_deduction_settings','leave_requests'
      )
  LOOP
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR ALL TO authenticated USING (public.is_payroll_admin()) WITH CHECK (public.is_payroll_admin());',
      'payroll_admin_only_' || t.tablename,
      t.tablename
    );
  END LOOP;
END $$;
