ALTER TABLE payroll_deduction_settings
ADD COLUMN IF NOT EXISTS late_grace_minutes INTEGER NOT NULL DEFAULT 5,
ADD COLUMN IF NOT EXISTS standard_work_minutes INTEGER NOT NULL DEFAULT 480,
ADD COLUMN IF NOT EXISTS break_allowed_minutes INTEGER NOT NULL DEFAULT 60,
ADD COLUMN IF NOT EXISTS overtime_multiplier NUMERIC(5,2) NOT NULL DEFAULT 1.25;

